[[constraint]]
  name = "github.com/eclipse/che-go-jsonrpc"
  version = "=0.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.2"

[[constraint]]
  version = "=2.2.1"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
