# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /build/che-plugin-broker
    steps:
      - checkout
      - run: 
          # copying is needed because of behavior of linter install script, see https://github.com/golangci/golangci-lint/issues/250
          name: "Install GolangCI linter"
          command: |
            wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.30.0
            sudo cp ./bin/golangci-lint $GOPATH/bin/
      - run: 
          name: "Build sources"
          command: |
            CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -ldflags '-w -s' -a -installsuffix cgo ./...
      - run: 
          name: "Run tests"
          command: |
            go test -v -race ./... -coverprofile=c.out -covermode=atomic
            go tool cover -html=c.out -o coverage.html
            cp coverage.html /tmp/artifacts
            cp c.out coverage.txt
      - run:
          name: "Save coverage to codecov"
          command: |
            bash <(curl -s https://codecov.io/bash)
      - run: 
          name: "Run GolangCI linter"
          command: |
            golangci-lint run -v
      - run:
          name: "Check go modules and vendor"
          command: |
            go mod tidy && go mod vendor
            if [[ ! -z $(git status -s) ]]
            then
              echo "Go mod state is not clean"
              exit 1
            fi
      - store_artifacts:
          path: /tmp/artifacts
